# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9694fa542e1f7a35456c35ebdd98b980c9baae1ec24738b8a5536cba95bb122c36979c984608b849f196d406ea04edfb5396242279a44fafc29f124f9126b17

test:
  secret_key_base: 7cd365c3bdcb588224670efe05d2bdc3ba3a061a5a7124d3456b6b637c04e81c4b6bc8202cc0b1ae607ef7343cac99a2cb08ed669ba37ca761b87f68567b4c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
